### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by anthonygore** [rakeshok/socket.io-client-cookie#4]
```
Error: Cannot find module '../socket.io-client/node_modules/engine.io-client/node_modules/xmlhttprequest'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/anthonygore/Projects/Codehike/socketio-test-server/node_modules/socket.io-client-cookie/index.js:5:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by anthonygore** [comment]
Actually I think it was a problem on my end, needed to run `npm install` again..

**Comment by diegobill** [comment]
Same problem. How can I set cookie using socket.io-client ???
